import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the complete audit artificial-intelligence course", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /aria-label="课件翻页"/);
  assert.match(html, /aria-controls="course-sidebar"/);
  assert.match(html, /隐藏侧栏/);
  assert.match(html, /id="course-sidebar"/);
  assert.match(html, /sidebar-open/);
  assert.match(html, /01<!-- --> \/ <!-- -->23/);
  assert.match(html, /上一页/);
  assert.match(html, /下一页/);
  assert.match(html, /打开目录/);
  assert.match(html, /class="hero course-slide"/);
  assert.match(html, /id="problem" class="lesson course-slide" hidden/);
  assert.match(html, /大模型和智能体的技术基础/);
  assert.match(html, /id="part-1"/);
  assert.match(html, /id="part-2"/);
  assert.match(html, /id="part-3"/);
  assert.match(html, /智能体基础与架构/);
  assert.match(html, /智能体在审计中的应用/);
  assert.doesNotMatch(html, /内容占位|本章建设中/);
  assert.match(html, /基于任务逻辑的编程/);
  assert.match(html, /经典机器学习/);
  assert.match(html, /历史核实样本\.xlsx/);
  assert.match(html, /报销明细\.xlsx/);
  assert.match(html, /发票台账\.xlsx/);
  assert.match(html, /开票金额/);
  assert.match(html, /BX-41610/);
  assert.match(html, /BX-42306/);
  assert.match(html, /合同正文.*860万元.*付款台账.*830万元/s);
  assert.match(html, /16×16/);
  assert.match(html, /两位室友自制人脸门禁|两个室友/);
  assert.match(html, /本课讨论大语言模型与智能体的基础概念/);
  assert.match(html, /第一部分.*大模型和智能体的技术基础/s);
  assert.match(html, /第二部分.*智能体基础与架构/s);
  assert.match(html, /第三部分.*智能体在审计中的应用/s);
  assert.match(html, /第一部分 · 章节目录/);
  assert.match(html, /images\/xiaoyu\.jpg/);
  assert.match(html, /两个室友.*门禁装上“眼睛”/s);
  assert.match(html, /笑雨.*骐源.*其他/s);
  assert.match(html, /门禁程序就执行开门/);
  assert.match(html, /门就保持关闭/);
  assert.doesNotMatch(html, /整堂课只审这一笔/);
  assert.match(html, /从神经网络到大语言模型/);
  assert.match(html, /普通神经网络已经可以通过训练学习规律，那么它还需要哪些关键变化，才能成为大语言模型/);
  assert.match(html, /同一套学习机制.*文字变成数字.*联系上下文.*海量文本预训练.*工程师怎样调用/s);
  assert.match(html, /大语言模型并不是另一种完全不同的人工智能/);
  assert.match(html, /大语言模型不是取代了神经网络/);
  assert.match(html, /审计人员发现这份合同存在异常，因此决定进一步核查/);
  assert.match(html, /Token 序列/);
  assert.match(html, /Embedding 向量/);
  assert.match(html, /模型实际接收和计算的是由文字转换而来的数字向量/);
  assert.match(html, /Transformer 让模型结合上下文处理语言/);
  assert.match(html, /Self-Attention/);
  assert.match(html, /从普通神经网络开始.*完整大语言模型.*放大一个 Block.*上下文计算.*重复堆叠.*回到模型输出/s);
  assert.match(html, /输入层.*隐藏计算层.*输出层/s);
  assert.match(html, /Token Embedding.*Position Information.*Transformer Block × N.*语言模型输出层/s);
  assert.match(html, /神经网络外部 · 输入预处理/);
  assert.match(html, /大语言模型 · 神经网络内部/);
  assert.match(html, /Transformer 对应这里/);
  assert.match(html, /Transformer 位于输入 Embedding 和最终输出层之间/);
  assert.match(html, /Masked Self-Attention.*Residual.*Feed-Forward Network/s);
  assert.match(html, /Attention负责从上下文中寻找和汇总相关信息|Attention 负责从上下文中寻找和汇总相关信息/);
  assert.match(html, /前馈神经网络负责进一步加工每个 Token 当前携带的信息|前馈神经网络 负责进一步加工每个 Token 当前携带的信息/);
  assert.match(html, /进一步核查.*存在异常.*因此.*决定/s);
  assert.match(html, /这份合同.*审计人员.*发现.*存在异常/s);
  assert.match(html, /不同层、不同Attention Head可能关注不同类型的关系/);
  assert.match(html, /Block 1.*Block 2 ….*Block N/s);
  assert.match(html, /较浅层.*中间层.*较深层/s);
  assert.match(html, /前文 Token.*Embedding.*Transformer × N.*最后一个位置.*语言模型输出层/s);
  assert.match(html, /核查.*58%.*调查.*19%.*分析.*12%.*处理.*6%.*其他.*5%/s);
  assert.match(html, /教学模拟 · 不代表真实模型输出/);
  assert.match(html, /合同.*异常.*进一步核查/s);
  assert.match(html, /根据前面的 Token，预测接下来最可能出现的 Token/);
  assert.match(html, /核查.*调查.*分析.*处理/s);
  assert.match(html, /普通神经网络.*输入样本.*作出预测.*计算误差.*调整权重/s);
  assert.match(html, /数据规模.*模型规模.*计算规模/s);
  assert.match(html, /反向传播/);
  assert.match(html, /工程师实际上怎样调用大语言模型/);
  assert.match(html, /一个使用 Transformer 的对话式大语言模型，整体是什么样子/);
  assert.match(html, /用户对话.*Chat Template.*Tokenizer.*Token ID.*Embedding 与位置信息.*Transformer Block × N.*LM Head.*下一 Token 概率/s);
  assert.match(html, /Prefill.*模型先读取已有上下文.*Decode.*每次预测并生成一个新 Token/s);
  assert.match(html, /KV Cache 是一次生成过程中的计算缓存/);
  assert.match(html, /model\.predictNextToken\(context\).*sample\(probabilities\).*isStopToken\(nextToken\).*streamToUser\(nextToken\).*context\.push\(nextToken\)/s);
  assert.match(html, /Greedy.*Temperature.*Top-p/s);
  assert.doesNotMatch(html, /Token 生成循环和智能体行动循环不是一回事/);
  assert.doesNotMatch(html, /工程师通常通过推理服务、开发工具包或调用接口使用模型/);
  assert.doesNotMatch(html, /messages：这一次交给模型的上下文/);
  assert.doesNotMatch(html, /用户在网页输入.*前端发送给后端.*后端组织请求.*接口访问模型.*模型生成Token.*网页展示回答/s);
  assert.doesNotMatch(html, /加入合同正文.*加入审计规则.*加入历史对话.*允许查询合同库.*开启智能体循环/s);
  assert.doesNotMatch(html, /const result = await llm\.generate/);
  assert.doesNotMatch(html, /instruction-model/);
  assert.doesNotMatch(html, /模型提供语言与推理能力，调用接口让程序可以使用模型/);
  assert.match(html, /如果任务不是回答一句话，而是让模型自己判断下一步做什么/);
  assert.match(html, /输入 → 大语言模型 → 输出.*目标 → 大语言模型判断 → 工具执行 → 观察结果/s);
  assert.doesNotMatch(html, /真实接口密钥、内部地址和敏感信息不能放在浏览器代码里/);
  assert.doesNotMatch(html, /新功能：全面上线，还是先小范围试点/);
  assert.doesNotMatch(html, /报告草稿还缺两处证据/);
  assert.doesNotMatch(html, /sshleifer\/tiny-gpt2/);
  assert.doesNotMatch(html, /历史对话.*由应用保存，并在本次调用中重新发送/s);
  assert.match(html, /工具反馈循环/);
  assert.match(html, /为什么仅有大语言模型还不够/);
  assert.match(html, /id="agent"/);
  assert.match(html, /id="agent-definition"/);
  assert.match(html, /id="agent-loop"/);
  assert.match(html, /id="agent-knowledge"/);
  assert.match(html, /id="agent-task"/);
  assert.match(html, /id="agent-planning"/);
  assert.match(html, /id="agent-case"/);
  assert.match(html, /id="agent-value"/);
  assert.match(html, /会回答一个问题，不等于能够完成一项工作/);
  assert.match(html, /6\.2 · 贯穿第二部分的案例.*合同甲的转分包风险识别.*证据、判断依据、不确定项和复核建议.*可复核的初步分析报告/s);
  assert.match(html, /智能体不是单一模型，而是一套运行系统/);
  assert.match(html, /7\.2 · 系统组成.*用户目标.*检查主合同甲的转分包风险，形成可复核的初步分析报告/s);
  assert.match(html, /8\.1 · 完整运行.*继续运行 06 提出的主合同甲任务.*承接 06 · 同一贯穿任务.*主合同甲转分包风险识别：九步运行轨迹/s);
  assert.match(html, /当前目标 · 与 06 相同.*选择的工具.*工具输入.*工具输出.*智能体下一步判断/s);
  assert.match(html, /知识型.*任务型.*规划型/s);
  assert.match(html, /海能智能体平台当前采用的业务分类/);
  assert.match(html, /制度知识助手/);
  assert.match(html, /会议纪要与任务分发/);
  assert.match(html, /输入 · 非结构化材料.*会议录音，外加议程与参会名单.*模型理解 · 结构化结果.*先验证转分包识别.*8 月中旬前.*表述含糊.*日期不明确，先暂停写入.*校验任务系统写入权限.*写入回执与通知结果/s);
  assert.match(html, /发现并调整/);
  assert.match(html, /关联程度：高/);
  assert.match(html, /结论、证据、推理依据、不确定性、后续建议和人工确认记录/);
  assert.match(html, /工具行动会放大错误影响/);
  assert.match(html, /身份与权限.*工具白名单.*人工审批.*异常中止.*结果复核/s);
  assert.match(html, /id="audit"/);
  assert.match(html, /id="audit-documents"/);
  assert.match(html, /id="audit-data"/);
  assert.match(html, /id="audit-report"/);
  assert.match(html, /id="audit-collaboration"/);
  assert.match(html, /id="audit-governance"/);
  assert.match(html, /从审计工作链理解三个智能体/);
  assert.match(html, /异构审计资料解析/);
  assert.match(html, /智能问数与数据分析/);
  assert.match(html, /智能生成审计报告/);
  assert.match(html, /三个智能体如何协作成完整审计系统/);
  assert.match(html, /目标是什么.*输入是什么.*需要什么知识.*可以调用什么工具.*权限和边界是什么.*输出怎样验证/s);
  assert.match(html, /主合同扫描件.*付款台账.*采购制度.*现场照片/s);
  assert.match(html, /页面拆分.*方向纠正.*去噪清晰化.*文字识别.*版面重建.*质量检测/s);
  assert.match(html, /文件路由与中间结果.*解析结果.*发现的问题.*统一证据对象/s);
  assert.match(html, /合同正文.*860万元.*付款台账.*830万元.*审批表.*860万元/s);
  assert.match(html, /用户身份.*业务语义层.*权限服务.*安全查询服务.*结果分析/s);
  assert.match(html, /总部审计人员.*天津分公司审计人员.*当前项目组成员/s);
  assert.match(html, /:授权单位范围.*由权限服务提供/s);
  assert.match(html, /仅允许只读单语句.*表字段白名单.*敏感字段脱敏.*完整查询日志/s);
  assert.match(html, /天津分公司.*4,280万元.*\+32%/s);
  assert.match(html, /报告结构.*类型模板.*问题表达.*制度依据.*批准案例.*风格规则/s);
  assert.match(html, /事实与证据.*审计分析.*报告表达/s);
  assert.match(html, /先确认提纲，再分章节生成/);
  assert.match(html, /接受并锁定.*退回修改.*恢复待审/s);
  assert.match(html, /证据-101.*证据-102.*证据-201.*规则-001/s);
  assert.match(html, /解析项目资料包.*查询历史采购数据.*形成结构化审计发现.*提交审计人员复核/s);
  assert.match(html, /证据对象.*查询结果对象.*审计发现对象.*报告对象/s);
  assert.match(html, /原始证据.*工具提取事实.*系统分析结果.*智能体建议.*审计人员确认.*正式审计结论/s);
  assert.match(html, /数据安全.*权限安全.*查询安全.*报告安全.*操作安全.*责任安全/s);
  assert.doesNotMatch(html, /运行一次受控智能问数|运行报告生成前质量门|运行完整审计流水线/);
  assert.doesNotMatch(html, /\b(?:ANN|Agent|AI|ML|CNN|RAG|SQL|OCR|GPU|CPU|HTML|HTTP|HTTPS|BPE|MLP|FFN|MVP|CRM|QR|PDF|CSV|URL)\b/);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview/);
});

test("supports direct and keyboard lecture pagination", async () => {
  const root = new URL("../", import.meta.url);
  const source = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /const coursePages:[\s\S]*id: "audit-governance"/);
  assert.match(source, /"ArrowRight", "PageDown"/);
  assert.match(source, /"ArrowLeft", "PageUp"/);
  assert.match(source, /event\.key === "Home"/);
  assert.match(source, /event\.key === "End"/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /setSidebarOpen\(value => !value\)/);
  assert.match(source, /matchMedia\("\(max-width: 760px\)"\)/);
  assert.match(source, /<CoursePager activeIndex=\{activePage\} onChange=\{goToPage\}/);
  assert.match(source, /querySelector<HTMLElement>\("\.paginated-course \.page"\)\?\.scrollTo/);
  assert.match(styles, /\.paginated-course \.page \{[\s\S]*height: calc\(100vh - 128px\);[\s\S]*overflow-y: auto;/);
  assert.match(styles, /\.course-pager \{[\s\S]*bottom: 12px;[\s\S]*height: 54px;/);
});

test("ships the independent training data and downloadable workbook", async () => {
  const root = new URL("../", import.meta.url);
  const csvUrl = new URL("public/toy_audit_case/classroom_training/ml_training_examples.csv", root);
  await Promise.all([
    access(csvUrl),
    access(new URL("public/toy_audit_case/toy_audit_case.xlsx", root)),
    access(new URL("public/toy_audit_case_download.zip", root)),
  ]);
  const rows = (await readFile(csvUrl, "utf8")).trim().split(/\r?\n/);
  assert.equal(rows.length, 301);
  assert.equal(rows.filter((row) => row.includes(",train,")).length, 240);
  assert.equal(rows.filter((row) => row.includes(",validation,")).length, 60);
});

test("ships the classic handwritten digits teaching subset", async () => {
  const csvUrl = new URL("../public/simple_audit_demo/digits_8x8_subset.csv", import.meta.url);
  const rows = (await readFile(csvUrl, "utf8")).trim().split(/\r?\n/);
  assert.equal(rows.length, 1301);
  assert.equal(rows.filter((row) => row.includes(",train,")).length, 1000);
  assert.equal(rows.filter((row) => row.includes(",test,")).length, 300);
  assert.match(rows[0], /pixel_00.*pixel_63/);
});

test("ships the locally cached Transformer reference figure", async () => {
  const imageUrl = new URL("../public/images/transformer-encoder-decoder-architecture.png", import.meta.url);
  const image = await readFile(imageUrl);
  assert.ok(image.byteLength > 100_000);
  assert.deepEqual([...image.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
});
